---
title: "finalMP2"
author: "GroupMP2E: Nukhbah Majid, Chhiring Lama, Joyce Huang"
date: "3/22/2019"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(dplyr)
library(plyr)
library(purrr)
library(ggthemes)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
##new_cand just filters for the candidates we want
filter_cand <- candidates %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP", cand_election_yr == "2012")

new_cand <- filter_cand %>%
  inner_join(contributions, by = "cand_id") %>%
  filter(transaction_type == "24A" | transaction_type == "24E", transaction_pgi == "G" | transaction_pgi == "G2012", cand_office == "S")

test24 <- new_cand %>%
  group_by(cand_name, transaction_type) %>%
  summarize(total_given = sum(transaction_amt))
```

Renaming `G2012` entries to `G` as they mean the same thing since the year is fixed as `2012`

```{r}
new_cand$transaction_pgi <- revalue(new_cand$transaction_pgi, c("G2012" = "G"))
```

```{r}
detach(package:plyr)
```


look at individual candidates
```{r fig.width=12, fig.height=11}
vector_state <- unique(new_cand$cand_office_state)

state_df <- data.frame(vector_state)

some_states <- c("CT", "MA", "RI")
some_df <- data.frame(some_states)

#call function on the names
new_data <- function(state_arg) {
  new_cand %>%
    filter(cand_office_state == state_arg) %>%
    group_by(transaction_type, cand_name, cand_office_state,
             cand_party_affiliation) %>%
    summarize(total = sum(transaction_amt)) %>%
    arrange(desc(total))
}

#####
teststate <- new_cand %>%
  group_by(cand_name, cand_office_state, 
           cand_party_affiliation) %>%
  summarize(total_given = sum(transaction_amt)) %>%
  filter(cand_office_state == "ME") %>%
  arrange(desc(total_given)) %>%
  ungroup()%>%
  top_n(2)

#map dataframe of states to the function
all_states <- map_df(some_df$some_states, new_data)
```

```{r fig.width=20, fig.height=20}
fill_c <- c("black", "purple")
fill_party <- c("blue", "red")

##transaction amount in 100,000s
ggplot(all_states, aes(x = cand_name, y = total/1000000, fill = cand_party_affiliation, color = transaction_type)) +
  geom_bar(stat = "identity", position = "dodge", size = 1.6) +
  scale_fill_manual("Candidate Party\nAffiliation",values = fill_party) +
  scale_color_manual("Contributions for:",labels = c("Opposing", "Supporting"), values = fill_c) +
  facet_wrap(~as.factor(cand_office_state), scales = "free") +
  scale_y_continuous(limits = c(0, 6.5), expand = c(0,0)) +
  geom_text(aes(label= total/1000000), position = position_dodge(width=0.9),
            vjust= -0.35, size = 7) +
  theme_economist() +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.4, size = 18), 
        axis.title.x = element_text(family = "Century Gothic", 
                                    color = "black", face = "bold", size = 24),
        axis.text.y = element_text(family = "Century Gothic", 
                                    color = "black", face = "bold", size = 20), 
        axis.title.y = element_text(family = "Century Gothic", 
                                    color = "black", face = "bold", size = 24),
        plot.title = element_text(family = "Century Gothic", 
                                    color = "black", face = "bold", size = 30),
        strip.text = element_text(family = "Century Gothic", face = "bold", size = 26),
        legend.text = element_text(family = "Century Gothic", face = "bold", size = 24),
        legend.title = element_text(family = "Century Gothic", face = "bold", size = 26)) +
  labs(title = "Amount Spent by the Committees 'For' and 'Against' Senate Candidates in New England\nStates\n", x = "Candidate Name", y = "Amount Contributed (in millions)") 
```
