---
title: "Joyce_test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(plyr)
library(purrr)
library(ggthemes)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
##new_cand just filters for the candidates we want
filter_cand <- candidates %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP", cand_election_yr == "2012", cand_office_state == "MA")

new_cand <- filter_cand %>%
  inner_join(contributions, by = "cand_id") %>%
  filter(transaction_type == "24A" | transaction_type == "24E", transaction_pgi == "G" | transaction_pgi == "G2012")
```

```{r}
##democrats
dem_data <- new_cand %>%
  filter(cand_party_affiliation == "DEM")

##republicans
rep_data <- new_cand %>%
  filter(cand_party_affiliation == "REP")
```

Filter for the general election candidates:

```{r}
dem_data <- dem_data %>%
  filter(transaction_pgi == "G" | transaction_pgi == "G2012")

rep_data <- rep_data %>%
  filter(transaction_pgi == "G" | transaction_pgi == "G2012")
```

Renaming `G2012` entries to `G` as they mean the same thing since the year is fixed as `2012`

```{r}
dem_data$transaction_pgi <- revalue(dem_data$transaction_pgi, c("G2012" = "G"))
rep_data$transaction_pgi <- revalue(rep_data$transaction_pgi, c("G2012" = "G"))
new_cand$transaction_pgi <- revalue(new_cand$transaction_pgi, c("G2012" = "G"))
```

```{r}
detach(package:plyr)
```


look at individual candidates
```{r fig.width=12, fig.height=11}
vector_name <- unique(new_cand$cand_name)

name_df <- data.frame(vector_name)

#call function on the names
new_data <- function(name_arg) {
  new_cand %>%
    filter(cand_name == name_arg) %>%
    group_by(transaction_type, cand_name, cand_party_affiliation) %>%
    summarize(total = sum(transaction_amt))
}

##name_order arranges the candidates in MA by total amount given to them
name_order <- new_cand %>%
  group_by(cand_name) %>%
  summarize(total_given = sum(transaction_amt)) %>%
  arrange(desc(total_given))

#map dataframe of names to the function
all_name <- map_df(name_df$vector_name, new_data)
```

```{r}
#facet_wrap arranges alphabetically by default, so in order to graph the plot in the correct order of the names we have to do this
all_name$cand_name <- factor(all_name$cand_name, levels = name_order$cand_name)

fill_c <- c("gray", "lightgreen")
fill_party <- c("blue", "red")

ggplot(all_name, aes(x = transaction_type, y = total, fill = transaction_type, color = cand_party_affiliation)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = fill_c) +
  scale_color_manual(values = fill_party) +
  theme(legend.position = "none") +
  facet_wrap(~as.factor(cand_name))
```

 +
  theme(strip.background = element_rect(fill="red"))+
  theme(strip.text = element_text(colour = 'white'))
