---
title: "mp2-nm"
author: "Nukhbah Majid"
date: "3/18/2019"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data


```{r, message=FALSE}
library(tidyverse)
library(dplyr)
library(plyr)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
fltr_cand <- candidates %>%
  filter(cand_office_state == "MA", cand_election_yr == "2012", cand_party_affiliation == "DEM" | cand_party_affiliation == "REP") %>%
  inner_join(contributions, by = "cand_id") %>%
  filter(transaction_type == "24A" | transaction_type == "24E")
```

## Filter according to party affiliation:

The `REP` data set:

```{r}
rep_data <- fltr_cand %>%
  filter(cand_party_affiliation == "REP")
```


The `DEM` data set: 

```{r}
dem_data <- fltr_cand %>%
  filter(cand_party_affiliation == "DEM")
```


```{r}
num_dem <- dem_data %>%
  summarize(n_distinct(cand_id))

num_rep <- rep_data %>%
  summarize(n_distinct(cand_id))

num_type_elections <- fltr_cand %>%
  summarize(n_distinct(transaction_pgi))
```

Since we are only working with the General Elections data for `2012`, filter accordingly:

```{r}
dem_data <- dem_data %>%
  filter(transaction_pgi == "G" | transaction_pgi == "G2012") 

rep_data <- rep_data %>%
  filter(transaction_pgi == "G" | transaction_pgi == "G2012")
```

Renaming `G2012` entries to `G` as they mean the same thing since the year is fixed as `2012`

```{r}
dem_data$transaction_pgi <- revalue(dem_data$transaction_pgi, c("G2012" = "G"))
rep_data$transaction_pgi <- revalue(rep_data$transaction_pgi, c("G2012" = "G"))
```


```{r}
num_dem <- dem_data %>%
  summarize(n_distinct(cand_id))

num_rep <- rep_data %>%
  summarize(n_distinct(cand_id))

num_type_elections <- fltr_cand %>%
  summarize(n_distinct(transaction_pgi))
```








