---
title: "Mini-Project 2"
author: "Your Name Here"
date: "2019-03-24"
output: 
  html_document:
    code_folding: show
---


## Loading the data

This project is so interesting and relevant to my life!

```{r, message=FALSE, echo = FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(plyr)
library(ggthemes)
```

```{r}
##filter by year, MA, by DEM and REP ----
filtered_data <- candidates %>%
  filter ( cand_election_yr == 2012)%>%
  filter (cand_office_state == "MA")%>%
  filter (cand_party_affiliation %in% c("DEM", "REP"))
```

```{r}
##joing candidates and contributions data frame ----

joined_data <- filtered_data %>%
  inner_join(contributions, by = "cand_id")%>%
  filter(transaction_type %in% c("24A", "24E"))%>%
  filter (transaction_pgi %in% c ("G", "G2012"))
```

```{r}
##making two datasets for two parties ----
dem <- joined_data %>%
  filter (cand_party_affiliation == "DEM")

rep <- joined_data %>%
  filter (cand_party_affiliation == "REP")
```

```{r}
dem$transaction_pgi <- revalue(dem$transaction_pgi, c("G2012" = "G"))
rep$transaction_pgi <- revalue(rep$transaction_pgi, c("G2012" = "G"))
```

```{r, echo = FALSE}
detach(package:plyr)
```

```{r}
##finding out contribution for individual candidates and plotting bar graph for DEm and REP ----

vector_name <- unique(joined_data$cand_name)
name_df <- data.frame(vector_name)

new_data <- function(name_arg) {
  joined_data %>%
    filter(cand_name == name_arg) %>%
    group_by(transaction_type, cand_name, cand_party_affiliation) %>%
    summarize(total = sum(transaction_amt))
}

all_name <- map_df(name_df$vector_name, new_data)

```

```{r}
##arranging by the amount of contribution ----
##name_order arranges the candidates in MA by total amount given to them
name_order <- joined_data %>%
  group_by(cand_name) %>%
  summarize(total_given = sum(transaction_amt)) %>%
  arrange(desc(total_given))

all_name$cand_name <- factor(all_name$cand_name, levels = name_order$cand_name)
```

```{r}
##making a bar graph to plot the summarise data ----
fill_cols <- c("gray","green")
ggplot(all_name, aes(x = transaction_type, y = total/100000, fill = transaction_type)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = fill_cols)+
  scale_y_continuous(expand = c(0, 0))+
  facet_wrap(~as.factor(cand_party_affiliation))+
  labs(title = "Amount Spent by the Committees'For' and 'Against' Candidates of the Two Major Parties", x = "Party Affiliation", y = "Amount donated (in $100,000)")
  
  
```

```{r}
## plotting data graph for each
fill_c <- c("blue", "gray")
ggplot(all_name, aes(x = transaction_type, y = total, fill = transaction_type)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = fill_c)+
  scale_y_continuous(expand = c(0, 0))+
  facet_wrap(~as.factor(cand_name))

```








