---
title: "senate_j"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(plyr)
library(purrr)
library(ggthemes)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
##new_cand just filters for the candidates we want
filter_cand <- candidates %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP", cand_election_yr == "2012")

new_cand <- filter_cand %>%
  inner_join(contributions, by = "cand_id") %>%
  filter(transaction_type == "24A" | transaction_type == "24E", transaction_pgi == "G" | transaction_pgi == "G2012", cand_office == "S")

test24 <- new_cand %>%
  group_by(cand_name, transaction_type) %>%
  summarize(total_given = sum(transaction_amt))
```

```{r}
##democrats
dem_data <- new_cand %>%
  filter(cand_party_affiliation == "DEM")

##republicans
rep_data <- new_cand %>%
  filter(cand_party_affiliation == "REP")
```

Filter for the general election candidates:

```{r}
dem_data <- dem_data %>%
  filter(transaction_pgi == "G" | transaction_pgi == "G2012")

rep_data <- rep_data %>%
  filter(transaction_pgi == "G" | transaction_pgi == "G2012")
```

Renaming `G2012` entries to `G` as they mean the same thing since the year is fixed as `2012`

```{r}
dem_data$transaction_pgi <- revalue(dem_data$transaction_pgi, c("G2012" = "G"))
rep_data$transaction_pgi <- revalue(rep_data$transaction_pgi, c("G2012" = "G"))
new_cand$transaction_pgi <- revalue(new_cand$transaction_pgi, c("G2012" = "G"))
```

```{r}
detach(package:plyr)
```


look at individual candidates
```{r fig.width=12, fig.height=11}
vector_state <- unique(new_cand$cand_office_state)

state_df <- data.frame(vector_state)

some_states <- c("CT", "MA", "RI")
some_df <- data.frame(some_states)

#call function on the names
new_data <- function(state_arg) {
  new_cand %>%
    filter(cand_office_state == state_arg) %>%
    group_by(transaction_type, cand_name, cand_office_state,
             cand_party_affiliation) %>%
    summarize(total = sum(transaction_amt)) %>%
    arrange(desc(total))
}

#####
teststate <- new_cand %>%
  group_by(cand_name, cand_office_state, 
           cand_party_affiliation) %>%
  summarize(total_given = sum(transaction_amt)) %>%
  filter(cand_office_state == "ME") %>%
  arrange(desc(total_given)) %>%
  ungroup()%>%
  top_n(2)

#map dataframe of states to the function
all_states <- map_df(some_df$some_states, new_data)
```

```{r fig.width=20, fig.height=20}
fill_c <- c("gray", "lightgreen")
fill_party <- c("blue", "red")

##transaction amount in 100,000s
ggplot(all_states, aes(x = cand_name, y = total/100,000, fill = transaction_type, color = cand_party_affiliation)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = fill_c) +
  scale_color_manual(values = fill_party) +
  facet_wrap(~as.factor(cand_office_state), scales = "free") +
  labs(title = "Amount Spent by the Committees'For' and 'Against' Senate Candidates in New England States", x = "Candidate Name", y = "Amount donated (in $100,000)")
```

making a temp change
